# Generated by Django 5.0.3 on 2024-04-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_motorcycles'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycles',
            name='engine_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='motorcycles',
            name='horsepower',
            field=models.IntegerField(null=True),
        ),
    ]
