# Generated by Django 5.0.3 on 2024-04-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_motorcycles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
