# Generated by Django 5.0.3 on 2024-04-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_motorcycles_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturare_pers_fizica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('oras', models.CharField(max_length=255)),
                ('judet', models.CharField(max_length=255)),
                ('adresa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('oras', models.CharField(max_length=255)),
                ('judet', models.CharField(max_length=255)),
                ('adresa', models.CharField(max_length=255)),
            ],
        ),
    ]
